chore: bump deps and major version
PabloSzx/mercurius-integration-testing pull request #8
Opened 2022-10-09 15:52 UTC by ZiiMakc

- update deps
- update major version
- update `peerDependencies` `mercurius` to 11

2022-10-09 16:54 UTC, mcollina requested changes

2022-10-09 16:54 UTC, mcollina commented on package.json
> +  "version": "6.0.0",
please revert this, we'll bump when we release

2022-10-14 08:28 UTC, mcollina approved these changes
lgtm

2022-10-14 17:58 UTC, ZiiMakc commented
@PabloSzx can we merge?

2022-10-14 18:02 UTC, PabloSzx approved these changes

2022-10-14 18:02 UTC, PabloSzx commented
seems good, thanks for @ me

2022-10-14 18:03 UTC, merged